name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit)
          - StandaloneWindows   # Build a Windows standalone
          - StandaloneWindows64 # Build a Windows 64-bit standalone
          - StandaloneLinux64   # Build a Linux 64-bit standalone
          - iOS                 # Build an iOS player
          - Android             # Build an Android .apk standalone app
          - WebGL               # Build a WebGL app

    # Troca o runner para macos-latest só para iOS
    runs-on: ${{ matrix.targetPlatform == 'iOS' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Free disk space (only on Android)
        if: matrix.targetPlatform == 'Android'
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Build project with Unity
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customParameters: -logFile -

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
